version: '3.4'

services:

  urlTesterdb:
    image: mcr.microsoft.com/mssql/server

  urlTester.api:
    image: ${DOCKER_REGISTRY-}urlTesterapi
    build:
      context: .
      dockerfile: URLTester.API/Dockerfile
