version: '3.4'

services:

  urlTesterdb:
    container_name: urlTesterdb
    environment:
      - SA_PASSWORD=Admin1234!!
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - 8600:1433
    networks:
      - urlTester_network

  urlTester.api:
    container_name: urlTester.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8001
      - ConnectionStrings:DefaultConnection=Server=urlTesterdb;Database=URLTesterDB;User Id=sa;Password=Admin1234!!;TrustServerCertificate=True;
      - Settings:BaseURL=http://localhost:8080
    ports:
      - "8080:8001"
    depends_on:
      - urlTesterdb
    networks:
      - urlTester_network

networks:
  urlTester_network:
    driver: bridge